environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\devtools\\ci\\appveyor\\run_with_env.cmd"
    CONDA_NPY: "113"
    PYTHONHASHSEED: "0"

install:
  - mkdir %USERPROFILE%\reports
  - python -c "import os; open(os.path.join(os.path.expanduser('~'),'reports', 'xunit.xml'),'w').write('hi')" 
  - ps: cd $env:USERPROFILE; ls
  - cd %USERPROFILE%;  ls reports
build: false # Not a C# project, build stuff at the test step instead.


on_finish:
  # upload test results to AppVeyor
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

  - ps: $wc = New-Object 'System.Net.WebClient';
        $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)",
        (Resolve-Path $env:USERPROFILE\reports\xunit.xml))
